db_file: "bot.db"

bot_url: "https://t.me/Pokcet_bot"


messages:
  responses:
    start: "access is required for authentication:\n%s"
    already_authorized: "You are authorizat now, send me link and I save this link for you"
    saved_successfully: "Link successfully saved"
    unknown_command: "I don't know this command"
  errors:
    default: "unknown error happend"
    invalid_url: "This is not valid link"
    unauthorized: "You are not authorized! Use command /start"
    unable_to_save: "Sorry something wrong, try letter"
