db_file: "bot.db"

bot_url: "https://t.me/Pokcet_bot"


messages:
  response:
    start: "Hello! To save links in your Pocket account, first, you need to give me access to it. To do this follow the link:\n%s"
    already_authorized: "You are already logged in with your Pocket account. Send a link to save."
    unknown_command: "I don't know this command!"
    link_saved: "The link was saved successfully!"
  error:
    default: "An unknown error has occurred."
    invalid_url:  "This is an invalid link."
    unable_to_save: "Failed to save the message to Pocket. Try later."
